### ISSUE TITLE
Real data with lungs shape

### ISSUE THREAD

**Issue by ccfbeltran** [eitcom/pyEIT#86]
Hi @liubenyuan,
I was using pyEIT its been some time. I made some eit hardware to be able to take some real data and use it with pyEIT. Actually, I would like to use it with GREIT . Can you give me some advice about the constants, the current and the frequency to use?

Thanks you very much for your work!

**Comment by liubenyuan** [comment]
Hi, we are using real data for lung imaging. We are using current injection on adjacent electrodes and measure the voltages differences on all adjacent electrodes (adj-adj mode). The measurements are complex-valued (demodulated) and we only use the real-valued part for EIT imaging.

Care should be taken on the polarity of these voltage difference measurements. If you take `abs` on the measurements of your lung imaging EIT system, you should modify the normalization script in the corresponding imaging algorithms as well.
