### ISSUE TITLE
The v0 calculated by the forward problem seems to be wrong

### ISSUE THREAD

**Issue by chenmo1515** [eitcom/pyEIT#95]
When the value of _perm_ defaults to all 1, either through `fwd.compute_jac()` or `fwd.solve_eit()`, the solved _v0_ is clearly wrong.
As an example, when the number of electrodes is 16, using the method of adjacent excitation-adjacent measurement, the calculated _v0_ is not all U-shaped, but appears to plateau at some locations.
![Figure_1](https://github.com/eitcom/pyEIT/assets/97735732/6d7cdec4-1abf-4a66-9e84-13b8a6256e00)
This is the _v0_ curve run with pyEIT, but the red circle in the figure below is clearly not correct.
![1695655788834](https://github.com/eitcom/pyEIT/assets/97735732/b4328737-970f-4806-bdb3-ce0cbfa520de)
This is not a coincidence! I troubleshot that the problem may be in the `solve_vectorized `function in `pyeit/fem.py`, where solving a system of linear equations using the sparse matrices _kg_ and _b_ appears rather obviously off at `i=11`.
Could you please troubleshoot and fix the problem?

**Comment by liubenyuan** [comment]
@chenmo1515 Hi, any progress on this issue on closing it?

**Comment by chenmo1515** [comment]
Sorry to bother you. When I wrote this comment, I realized that the problem I was talking about was due to a different order of excitation-measurement, that's my mistake.
